small update

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -9,14 +9,24 @@
 # it wants to stop the commit.
 #
 
-grep TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java
+# make sure table types are Temporary (i.e. not Standard)
+grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java
 if [ $? == 0 ]; then
 	echo "src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java contains TableTypes.Standard, aborting"
 	exit 1
 fi
-grep TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java
+
+# make sure table types are Temporary (i.e. not Standard)
+grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java
 if [ $? == 0 ]; then
 	echo "src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java contains TableTypes.Standard, aborting"
+	exit 1
+fi
+
+# make sure table create statements are the current ones (i.e. not versions)
+grep -i -e "DATABASE_CREATE.*_v" src/com/eleybourn/bookcatalogue/database/CatalogueDBHelper.java
+if [ $? == 0 ]; then
+	echo "src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java contains versioned create table statements, aborting"
 	exit 1
 fi
 
