snapshot... Styles are now XML. Exports XML; and far to many other changes... Code needs a real good test cycle now; crashes when least expected

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -3,22 +3,35 @@
 # Copy this into .git/hooks/
 # it's not functional in the project root !
 #
+# An example hook script to verify what is about to be committed.
 # Called by "git commit" with no arguments.  The hook should
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
 #
 
+#
 # make sure table types are Temporary (i.e. not Standard)
-grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java
-if [ $? == 0 ]; then
+#
+function checkTempTableUsage {
+  grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java
+  if [ $? == 0 ]; then
 	echo "src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java contains TableTypes.Standard, aborting"
 	exit 1
-fi
+  fi
 
-# make sure table types are Temporary (i.e. not Standard)
-grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java
-if [ $? == 0 ]; then
+  grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java
+  if [ $? == 0 ]; then
 	echo "src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java contains TableTypes.Standard, aborting"
+	exit 1
+  fi
+}
+
+
+
+# make sure table create statements are the current ones (i.e. not versions)
+grep -i -e "DATABASE_CREATE.*_v" src/com/eleybourn/bookcatalogue/database/CatalogueDBHelper.java
+if [ $? == 0 ]; then
+	echo "src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java contains versioned create table statements, aborting"
 	exit 1
 fi
 
